---
- hosts: "turret"
  become: false
  vars:
    # outside of yaml, actual regex looks like this ==> (?!.*\/).+
    git_repo_path_pretrim: >
      {{ git_repo_url | regex_search('(?!.*\/).+') | regex_replace('.git', '') }}
  tasks:
#================================
  - set_fact:
      git_repo_path: "{{ git_repo_path_pretrim | trim }}"
#================================
  - name: Create temporary directory
    tempfile:
      state: directory
    register: tmpdir
#================================
  - name: Git clone project locally
    include_role:
      name: ansible_git
      tasks_from: clone
    vars:
      git_url: "{{ git_repo_url }}"
      git_token: "{{ lookup('env', 'MY_PA_TOKEN') }}"
      git_branch: "{{ git_repo_branch | default('main') }}"
      base_working_dir: "{{ tmpdir.path }}"
#================================
  - debug:
      msg:
        - "Temporary directory path  ==> {{ tmpdir.path }}"
        - "git_repo_path ==> {{ git_repo_path }}"
#================================
  - name: list temporary directory contents
    find:
      paths: "{{ tmpdir.path }}/{{ git_repo_path }}"
      patterns: "*"
      excludes: 'collections,roles'
      recurse: no
      file_type: directory
    register: found_directories

  - debug:
      msg: "{{ [item.path] }} "
    with_items: "{{ found_directories.files }}"
#================================
  - name: Recursively select yml files
    find:
      paths: "{{ [item.path] }}"
      patterns: '*.yml'
      recurse: yes
    with_items: "{{ found_directories.files }}"
    register: files_to_change

  #- debug:
  #    msg: "{{ [item.path] }} "
  #  with_items: "{{ files_to_change.files }}"
  - debug:
      msg: "{{ [item] }} "
    with_items: "{{ files_to_change.results }}"
#================================
  run_once: yes
