---
- hosts: "turret"
  become: true
  vars:
    # outside of yaml, actual regex looks like this ==> (?!.*\/).+
    git_repo_path: "{{ git_url | regex_search('(?!.*\/).+') | regex_replace('.git', '') }}"
  tasks:
#================================
  - name: Create temporary directory
    tempfile:
      state: directory
    register: tmpdir
#================================
  - name: Git clone project locally
    include_role:
      name: ansible_git
      tasks_from: clone
    vars:
      git_url: "{{ git_repo_url }}"
      git_token: "{{ lookup('env', 'MY_PA_TOKEN') }}"
      git_branch: "{{ git_repo_branch | default('main') }}"
      base_working_dir: "{{ tmpdir.path }}"
#================================
  - debug:
      msg:
        - "Temporary directory path  ==> {{ tmpdir.path }}"
#================================
  - name: list temporary directory contents
    find:
      paths: "{{ tmpdir.path }}/{{ git_repo_path }}"
      patterns: "*"
      recurse: no
      file_type: directory
    register: found_directories

  - debug:
      msg: "{{ [item.path] }} "
    with_items: "{{ found_directories.files }}"
#================================
  run_once: yes
