---
plugin: aws_ec2
regions:
  - us-east-2
filters:
  tag:ContentView: CentOS7
  tag:Environment: Dev
  tag:Student: student1
  tag:guid: oe01
hostnames:
  - tag:NodeName
compose:
  ansible_host: private_ip_address
  ansible_user: "'centos'"
keyed_groups:
  - prefix: cv
    key: tags['ContentView']
  - prefix: env
    key: tags['ContentView'] ~ '_' ~ tags['Environment']
  - prefix: os
    key: tags['foreman_operatingsystem_name']
